### ISSUE TITLE
How desactivate the check of SSL/TLS certificate?

### ISSUE THREAD

**Issue by yeplaa** [hawkular/hawkular-alerts#498]
Hello,

On Hawkular alerts, i would like to connect to an elastic search exposed in HTTPS but i would like desactivate the check of SSL/TLS certificate. Is is possible?

Thank's
Loïc

**Comment by lucasponce** [comment]
Hi @yeplaa,

As commented, Hawkular Alerts uses the Elasticsearch java client, and this delegates in java.net.ssl config.

So, at the moment, to run that scenario, we should implement some kind of "trust every source" and that is not yet in place.

An alternative way is to import the certificate of the Elasticsearch server in a truststore and add it in the standard way that JSSE describes.

http://www.hawkular.org/community/docs/developer-guide/alerts-v2.html#_elasticsearch_security

Hope this helps.

**Comment by yeplaa** [comment]
Hi,

Thank's for your help. By integrating the CA in the default keystore of DockerImage Jboss of Hawkuar Alerts (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.el7_3.x86_64/jre/lib/security/cacerts), the certificates are validated, it's works !!
