### ISSUE TITLE
Heavy sorting of alert list result

### ISSUE THREAD

**Issue by ehsanjavadynia** [hawkular/hawkular-alerts#505]
Hi, I've been working with hawkular alert for a while and I realized that it's really slow on sorting alerts.
When I read the code I found this line:
https://github.com/hawkular/hawkular-alerts/blob/b4a0c2909b38e03e72cc1828219562ee8fcbf426/engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImpl.java#L869
I'm don't know why you used collection sort. Isn't it better to use pagination and sort of infinispan itself?
instead of :
https://github.com/hawkular/hawkular-alerts/blob/b4a0c2909b38e03e72cc1828219562ee8fcbf426/engine/src/main/java/org/hawkular/alerts/engine/impl/ispn/IspnAlertsServiceImpl.java#L544
We can use this and do the pagination in infinispan:
```java
private List<IspnEvent> addPagingIfNecessaryAndGetList(Pager pager, StringBuilder query) {
        if (null != pager && null != pager.getOrder() && !pager.getOrder().isEmpty()) {
            query.append(" ORDER BY ");
            boolean isFirst = true;
            for (Order order : pager.getOrder()) {
                if (isFirst) {
                    isFirst = false;
                } else {
                    query.append(", ");
                }
                query.append(order.getField());
                query.append(order.isAscending() ? " ASC " : " DESC ");
            }
        }

        Query queryDsl = queryFactory.create(query.toString());
        if (null != pager) {
            queryDsl.startOffset(pager.getStart());
            queryDsl.maxResults(pager.getPageSize());
        }
        return queryDsl.list();
    }
```

**Comment by jshaughn** [comment]
Hi @ehsanjavadynia,   I'm sure the collections sort was probably sufficient at the time but your approach may well be better.  The Hawkular project is no longer maintained and so there will not be any new releases.  But if it will help you to have your change in the code base you can create a PR and I can merge it.

**Comment by ehsanjavadynia** [comment]
Hi @jshaughn, that's a pity. We really liked this project! Thanks for your great work on this project. Maybe we make a fork of this project.

**Comment by jshaughn** [comment]
Thanks @ehsanjavadynia , I'm happy to know you find it useful!
